SELECT REPLACE(REPLACE(DELTA_VALUE, '-P', ''), '-I', '') AS IDENTITY_TAX_NUMBER,
       "CALC_MOBILEPHONE_1" AS MOBILEPHONE,
		COMPOSECRML1.FNC_PHN_DAHILI('MAP_CRM_ABS_COMM_RAW_COMPOSECRML1_DS',"CALC_MOBILEPHONE_1") AS mobilephone_dahili, 
		COMPOSECRML1.FNC_PHN_TELNO1('MAP_CRM_ABS_COMM_RAW_COMPOSECRML1_DS',"CALC_MOBILEPHONE_1") AS mobilephone_telno1,
		COMPOSECRML1.FNC_PHN_TELNO2('MAP_CRM_ABS_COMM_RAW_COMPOSECRML1_DS',"CALC_MOBILEPHONE_1") AS mobilephone_telno2,
		COMPOSECRML1.FNC_PHN_TELNO3('MAP_CRM_ABS_COMM_RAW_COMPOSECRML1_DS',"CALC_MOBILEPHONE_1") AS mobilephone_telno3,	   
		composecrml1.fnc_phn_isvalid('MAP_CRM_ABS_COMM_RAW_COMPOSECRML1_DS',"CALC_MOBILEPHONE_1")  AS mobilephone_val,
      "CALC_TELEPHONE3_1" AS TELEPHONE3,
		COMPOSECRML1.FNC_PHN_DAHILI('MAP_CRM_ABS_COMM_RAW_COMPOSECRML1_DS',"CALC_TELEPHONE3_1") AS telephone3_dahili,
		COMPOSECRML1.FNC_PHN_TELNO1('MAP_CRM_ABS_COMM_RAW_COMPOSECRML1_DS',"CALC_TELEPHONE3_1") AS telephone3_telno1,
		COMPOSECRML1.FNC_PHN_TELNO2('MAP_CRM_ABS_COMM_RAW_COMPOSECRML1_DS',"CALC_TELEPHONE3_1") AS telephone3_telno2,
		COMPOSECRML1.FNC_PHN_TELNO3('MAP_CRM_ABS_COMM_RAW_COMPOSECRML1_DS',"CALC_TELEPHONE3_1") AS telephone3_telno3,
 composecrml1.fnc_phn_isvalid('MAP_CRM_ABS_COMM_RAW_COMPOSECRML1_DS',"CALC_TELEPHONE3_1") as telephone3_val,
      "CALC_EMAILADDRESS1_1" AS EMAILADDRESS1,
		COMPOSECRML1.FNC_EMAIL_PROCESSED('MAP_CRM_ABS_COMM_RAW_COMPOSECRML1_DS',"CALC_EMAILADDRESS1_1") AS emailaddress1_processed,
		COMPOSECRML1.FNC_EMAIL_QUALITY_CODE('MAP_CRM_ABS_COMM_RAW_COMPOSECRML1_DS',"CALC_EMAILADDRESS1_1") AS emailaddress1_quality_code,
		COMPOSECRML1.FNC_EMAIL_ISVALID('MAP_CRM_ABS_COMM_RAW_COMPOSECRML1_DS',"CALC_EMAILADDRESS1_1") as emailaddress1_val,
      CASE
            WHEN TRIM(KOMMART) = 'I' THEN
             KENNUNG
            ELSE
             ''
          END AS WEBSITE,
      "CALC_CDVGSMINFO_1" AS CDVGSMINFO,
		COMPOSECRML1.FNC_PHN_DAHILI('MAP_CRM_ABS_COMM_RAW_COMPOSECRML1_DS',"CALC_CDVGSMINFO_1") AS cdvgsminfo_dahili,
		COMPOSECRML1.FNC_PHN_TELNO1('MAP_CRM_ABS_COMM_RAW_COMPOSECRML1_DS',"CALC_CDVGSMINFO_1") AS cdvgsminfo_telno1,
		COMPOSECRML1.FNC_PHN_TELNO2('MAP_CRM_ABS_COMM_RAW_COMPOSECRML1_DS',"CALC_CDVGSMINFO_1") AS cdvgsminfo_telno2,
		COMPOSECRML1.FNC_PHN_TELNO3('MAP_CRM_ABS_COMM_RAW_COMPOSECRML1_DS',"CALC_CDVGSMINFO_1") AS cdvgsminfo_telno3,	 
        COMPOSECRML1.FNC_PHN_ISVALID('MAP_CRM_ABS_COMM_RAW_COMPOSECRML1_DS',"CALC_CDVGSMINFO_1") AS cdvgsminfo_val,		
      "CALC_CDVEMAILINFO_1" AS CDVEMAILINFO,
		COMPOSECRML1.FNC_EMAIL_PROCESSED('MAP_CRM_ABS_COMM_RAW_COMPOSECRML1_DS',"CALC_CDVEMAILINFO_1") AS cdvemailinfo_processed,
		COMPOSECRML1.FNC_EMAIL_QUALITY_CODE('MAP_CRM_ABS_COMM_RAW_COMPOSECRML1_DS',"CALC_CDVEMAILINFO_1") AS cdvemailinfo_quality_code,
		COMPOSECRML1.FNC_EMAIL_ISVALID('MAP_CRM_ABS_COMM_RAW_COMPOSECRML1_DS',"CALC_CDVEMAILINFO_1") AS cdvemailinfo_val,
           KENNUNG,
           KENNUNG_DT,
           ODS_COMMIT_DATE AS UPDATE_DATE,
           KO# KO#_KEY,
           DELTA_VALUE DELTA_VALUE_KEY,
           SRC_SYS_NM SRC_SYS_NM_KEY
   FROM (SELECT 
              T.CALC_CDVEMAILINFO_1,
       		  T.CALC_CDVGSMINFO_1,
        	  T.CALC_EMAILADDRESS1_1,
         	  T.CALC_TELEPHONE3_1,
       		  T.CALC_MOBILEPHONE_1,
              T.KO#,
              T.KOMMART,
              T.KENNUNG,
              T.KENNUNG_DT,
              T.KOMMQUELLE,
              T.KOMMPRIOR,
              T.PERS#,
              T.KZPRIDIE,
              T.KOMMANM,
              T.KZKOMMDATVALID,
              T.KZWERBE_ERL,
              D.SRC_SYS_NM,
              D.DELTA_VALUE,
              T.ODS_COMMIT_DATE
         FROM "COMPOSECRML1"."TDWH_CRM_TKOMM_HUB" T
         JOIN "COMPOSECRML1"."TDWH_CRM_ABS_DELTA_COMMADDR_HUB" /*"COMPOSECRML1"."TDWH_CRM_ABS_DELTA_HUB"*/ D
           ON T.PERS# = D.MAX_PERS#
        WHERE --T.KENNUNG IS NOT NULL AND
         (
         (T.RUNNO_UPDATE > (select PROCESSED_RUNNO FROM COMPOSECRML1.STG_RUN_CONFIG WHERE config_name = 'STG_ABS_L1') AND T.RUNNO_UPDATE <= (select SRC_MAX_RUNNO FROM COMPOSECRML1.STG_RUN_CONFIG WHERE config_name = 'STG_ABS_L1'))
          OR
          (D.RUNNO_UPDATE > (select PROCESSED_RUNNO FROM COMPOSECRML1.STG_RUN_CONFIG WHERE config_name = 'STG_ABS_L1') AND D.RUNNO_UPDATE <= (select SRC_MAX_RUNNO FROM COMPOSECRML1.STG_RUN_CONFIG WHERE config_name = 'STG_ABS_L1'))
         )
      )