
CREATE TABLE REF_EMAIL_DOMAIN 
   (	EMAIL_DOMAIN VARCHAR2(300)
   );
   
   
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('agency');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('aero');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('asia');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('biz');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('cat');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('com');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('coop');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('info');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('int');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('jobs');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('mobi');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('museum');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('name');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('net');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('org');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('post');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('pro');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('tel');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('travel');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('edu');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('gov');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('mil');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ac');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ad');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ae');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('af');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ag');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ai');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('al');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('am');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('an');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ao');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('aq');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ar');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('as');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('at');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('au');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('aw');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ax');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('az');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ba');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('bb');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('bd');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('be');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('bf');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('bg');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('bh');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('bi');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('bj');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('bm');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('bn');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('bo');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('br');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('bs');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('bt');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('bv');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('bw');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('by');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('bz');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ca');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('cc');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('cd');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('cf');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('cg');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ch');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ci');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ck');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('cl');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('cm');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('cn');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('co');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('cr');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('cs');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('cu');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('cv');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('cx');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('cy');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('cz');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('dd');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('de');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('dj');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('dk');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('dm');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('do');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('dz');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ec');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ee');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('eg');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('eh');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('er');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('es');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('et');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('eu');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('fi');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('fj');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('fk');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('fm');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('fo');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('fr');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ga');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('gb');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('gd');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ge');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('gf');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('gg');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('gh');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('gi');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('gl');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('gm');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('gn');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('gp');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('gq');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('gr');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('gs');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('gt');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('gu');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('gw');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('gy');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('hk');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('hm');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('hn');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('hr');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ht');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('hu');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('id');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ie');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('il');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('im');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('in');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('io');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('iq');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ir');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('is');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('it');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('je');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('jm');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('jo');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('jp');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ke');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('kg');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('kh');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ki');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('km');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('kn');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('kp');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('kr');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('kw');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ky');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('kz');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('la');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('lb');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('lc');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('li');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('lk');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('lr');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ls');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('lt');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('lu');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('lv');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ly');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ma');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('mc');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('md');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('me');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('mg');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('mh');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('mk');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ml');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('mm');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('mn');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('mo');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('mp');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('mq');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('mr');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ms');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('mt');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('mu');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('mv');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('mw');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('mx');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('my');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('mz');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('na');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('nc');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ne');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('nf');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ng');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ni');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('nl');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('no');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('np');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('nr');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('nu');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('nz');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('om');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('pa');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('pe');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('pf');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('pg');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ph');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('pk');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('pl');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('pm');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('pn');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('pr');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ps');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('pt');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('pw');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('py');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('qa');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('re');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ro');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('rs');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ru');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('rw');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('sa');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('sb');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('sc');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('sd');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('se');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('sg');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('sh');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('si');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('sj');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('sk');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('sl');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('sm');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('sn');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('so');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('sr');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ss');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('st');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('su');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('sv');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('sx');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('sy');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('sz');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('tc');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('td');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('tf');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('tg');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('th');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('tj');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('tk');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('tl');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('tm');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('tn');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('to');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('tp');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('tr');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('tt');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('tv');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('tw');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('tz');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ua');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ug');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('uk');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('us');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('uy');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('uz');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('va');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('vc');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ve');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('vg');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('vi');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('vn');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('vu');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('wf');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ws');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('ye');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('yt');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('yu');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('za');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('zm');
INSERT INTO REF_EMAIL_DOMAIN
(EMAIL_DOMAIN)
VALUES('zw');

CREATE TABLE REF_EMAIL_NOISE 
   (	EMAIL_NOISE VARCHAR2(300)
   )

INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('aaaaaaaaaa');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('aaaaaaaaa');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('aaaaaaaa');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('aaaaaaa');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('aaaaaa');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('aaaaa');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('aaaa');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('aaa');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('bbbbbbbbbb');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('bbbbbbbbb');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('bbbbbbbb');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('bbbbbbb');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('bbbbbb');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('bbbbb');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('bbbb');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('bbb');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('cccccccccc');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ccccccccc');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('cccccccc');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ccccccc');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('cccccc');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ccccc');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('cccc');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ccc');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('çççççççççç');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ççççççççç');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('çççççççç');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ççççççç');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('çççççç');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ççççç');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('çççç');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ççç');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('dddddddddd');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ddddddddd');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('dddddddd');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ddddddd');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('dddddd');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ddddd');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('dddd');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ddd');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('eeeeeeeeee');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('eeeeeeeee');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('eeeeeeee');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('eeeeeee');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('eeeeee');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('eeeee');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('eeee');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('eee');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ffffffffff');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('fffffffff');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ffffffff');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('fffffff');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ffffff');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('fffff');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ffff');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('fff');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('gggggggggg');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ggggggggg');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('gggggggg');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ggggggg');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('gggggg');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ggggg');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('gggg');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ggg');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ğğğğğğğğğğ');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ğğğğğğğğğ');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ğğğğğğğğ');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ğğğğğğğ');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ğğğğğğ');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ğğğğğ');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ğğğğ');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ğğğ');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('hhhhhhhhhh');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('hhhhhhhhh');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('hhhhhhhh');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('hhhhhhh');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('hhhhhh');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('hhhhh');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('hhhh');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('hhh');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ıııııııııı');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ııııııııı');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ıııııııı');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ııııııı');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ıııııı');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ııııı');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ıııı');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ııı');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('iiiiiiiiii');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('iiiiiiiii');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('iiiiiiii');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('iiiiiii');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('iiiiii');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('iiiii');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('iiii');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('iii');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('jjjjjjjjjj');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('jjjjjjjjj');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('jjjjjjjj');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('jjjjjjj');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('jjjjjj');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('jjjjj');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('jjjj');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('jjj');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('kkkkkkkkkk');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('kkkkkkkkk');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('kkkkkkkk');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('kkkkkkk');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('kkkkkk');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('kkkkk');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('kkkk');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('kkk');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('llllllllll');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('lllllllll');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('llllllll');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('lllllll');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('llllll');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('lllll');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('llll');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('lll');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('mmmmmmmmmm');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('mmmmmmmmm');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('mmmmmmmm');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('mmmmmmm');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('mmmmmm');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('mmmmm');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('mmmm');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('mmm');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('nnnnnnnnnn');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('nnnnnnnnn');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('nnnnnnnn');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('nnnnnnn');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('nnnnnn');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('nnnnn');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('nnnn');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('nnn');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('oooooooooo');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ooooooooo');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('oooooooo');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ooooooo');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('oooooo');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ooooo');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('oooo');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ooo');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('öööööööööö');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ööööööööö');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('öööööööö');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ööööööö');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('öööööö');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ööööö');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('öööö');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ööö');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('pppppppppp');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ppppppppp');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('pppppppp');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ppppppp');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('pppppp');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ppppp');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('pppp');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ppp');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('qqqqqqqqqq');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('qqqqqqqqq');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('qqqqqqqq');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('qqqqqqq');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('qqqqqq');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('qqqqq');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('qqqq');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('qqq');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('rrrrrrrrrr');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('rrrrrrrrr');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('rrrrrrrr');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('rrrrrrr');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('rrrrrr');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('rrrrr');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('rrrr');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('rrr');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ssssssssss');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('sssssssss');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ssssssss');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('sssssss');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ssssss');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('sssss');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ssss');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('sss');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('şşşşşşşşşş');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('şşşşşşşşş');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('şşşşşşşş');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('şşşşşşş');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('şşşşşş');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('şşşşş');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('şşşş');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('şşş');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('tttttttttt');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ttttttttt');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('tttttttt');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ttttttt');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('tttttt');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ttttt');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('tttt');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('ttt');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('uuuuuuuuuu');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('uuuuuuuuu');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('uuuuuuuu');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('uuuuuuu');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('uuuuuu');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('uuuuu');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('uuuu');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('uuu');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('üüüüüüüüüü');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('üüüüüüüüü');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('üüüüüüüü');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('üüüüüüü');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('üüüüüü');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('üüüüü');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('üüüü');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('üüü');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('vvvvvvvvvv');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('vvvvvvvvv');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('vvvvvvvv');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('vvvvvvv');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('vvvvvv');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('vvvvv');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('vvvv');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('vvv');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('wwwwwwwwww');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('wwwwwwwww');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('wwwwwwww');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('wwwwwww');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('wwwwww');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('wwwww');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('wwww');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('www');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('xxxxxxxxxx');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('xxxxxxxxx');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('xxxxxxxx');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('xxxxxxx');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('xxxxxx');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('xxxxx');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('xxxx');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('xxx');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('yyyyyyyyyy');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('yyyyyyyyy');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('yyyyyyyy');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('yyyyyyy');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('yyyyyy');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('yyyyy');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('yyyy');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('yyy');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('zzzzzzzzzz');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('zzzzzzzzz');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('zzzzzzzz');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('zzzzzzz');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('zzzzzz');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('zzzzz');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('zzzz');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('zzz');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('!!!!!!!!!!');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('!!!!!!!!!');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('!!!!!!!!');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('!!!!!!!');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('!!!!!!');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('!!!!!');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('!!!!');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('!!!');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('!!');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('""""""""""""""');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('""""""""""""');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('""""""""""""');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('""""""""""');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('""""""""""');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('"""""""""');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('"""""""""');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('"""""""');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('"""""""');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('??????????');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('?????????');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('????????');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('???????');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('??????');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('?????');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('????');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('???');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('??');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('$$$$$$$$$$');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('$$$$$$$$$');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('$$$$$$$$');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('$$$$$$$');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('$$$$$$');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('$$$$$');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('$$$$');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('$$$');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('$$');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('%%%%%%%%%%');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('%%%%%%%%%');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('%%%%%%%%');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('%%%%%%%');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('%%%%%%');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('%%%%%');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('%%%%');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('%%%');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('%%');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('^^^^^^^^^^');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('^^^^^^^^^');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('^^^^^^^^');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('^^^^^^^');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('^^^^^^');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('^^^^^');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('^^^^');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('^^^');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('^^');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('&&&&&&&&&&');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('&&&&&&&&&');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('&&&&&&&&');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('&&&&&&&');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('&&&&&&');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('&&&&&');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('&&&&');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('&&&');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('&&');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('**********');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('*********');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('********');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('*******');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('******');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('*****');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('****');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('***');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('**');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('@@@@@@@@@@');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('@@@@@@@@@');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('@@@@@@@@');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('@@@@@@@');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('@@@@@@');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('@@@@@');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('@@@@');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('@@@');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('@@');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES(';;;;;;;;;;');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES(';;;;;;;;;');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES(';;;;;;;;');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES(';;;;;;;');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES(';;;;;;');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES(';;;;;');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES(';;;;');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES(';;;');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES(';;');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('::::::::::');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES(':::::::::');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('::::::::');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES(':::::::');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('::::::');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES(':::::');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('::::');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES(':::');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('::');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('##########');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('#########');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('########');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('#######');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('######');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('#####');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('####');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('###');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('##');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('~~~~~~~~~~');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('~~~~~~~~~');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('~~~~~~~~');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('~~~~~~~');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('~~~~~~');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('~~~~~');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('~~~~');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('~~~');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('~~');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('??????????');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('?????????');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('????????');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('???????');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('??????');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('?????');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('????');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('???');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('??');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('?');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('++++++++++');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('+++++++++');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('++++++++');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('+++++++');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('++++++');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('+++++');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('++++');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('+++');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('++');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('..........');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('.........');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('........');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('.......');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('......');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('.....');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('....');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('...');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('..');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('NULL');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('DUPLICATE');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('*');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('00000000');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('----------');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('---------');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('--------');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('-------');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('------');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('-----');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('----');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('---');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('--');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('Dummy');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('-');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('Do Not Use');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('To Be Remo');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('Remove');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('Delete');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('999');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('Not Provid');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('none');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('UNKNOWN');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('¿¿¿');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('¿');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('¿¿');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('¿¿¿¿');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('¿¿¿¿¿');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('¿¿¿¿¿¿');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('¿¿¿¿¿¿¿');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('¿¿¿¿¿¿¿¿');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('¿¿¿¿¿¿¿¿¿');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('¿¿¿¿¿¿¿¿¿¿');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('1111111');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('2222222');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('3333333');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('4444444');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('5555555');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('6666666');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('7777777');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('8888888');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('9999999');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('0000000');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('1234567');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('BOŞ');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('YOK');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('Belirtilmemiş');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('Bilinmiyor');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('EMPTY');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('NULL');
INSERT INTO REF_EMAIL_NOISE
(EMAIL_NOISE)
VALUES('xx');   

commit;

CREATE TABLE REPLACEMENT_TABLE 
   (	SUBJECT VARCHAR2(50), 
	STEP_NAME VARCHAR2(50), 
	RUN_ORDER NUMBER, 
	SEARCH_STRING VARCHAR2(100), 
	REPLACE_STRING VARCHAR2(100)
   );

INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 1, '@@', '@');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('PHONE', 'STEP4', 1, '00900', 'x');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('PHONE', 'STEP1-3', 1, '--', '-');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('PHONE', 'STEP1-3', 1, '---', '-');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('PHONE', 'STEP1-3', 1, '----', '-');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('PHONE', 'STEP1-3', 1, '-----', '-');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('PHONE', 'STEP1-3', 1, '------', '-');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('PHONE', 'STEP1-1', 1, 'İ', 'I');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('PHONE', 'STEP1-1', 1, 'i', 'I');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('PHONE', 'STEP1-1', 1, 'Ü', 'U');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('PHONE', 'STEP1-1', 1, 'ü', 'U');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('PHONE', 'STEP1-1', 1, 'ç', 'C');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('PHONE', 'STEP1-1', 1, 'Ç', 'C');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('PHONE', 'STEP1-1', 1, 'Ş', 'S');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('PHONE', 'STEP1-1', 1, 'ş', 'S');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('PHONE', 'STEP1-1', 1, 'ğ', 'G');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('PHONE', 'STEP1-1', 1, 'Ğ', 'G');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('PHONE', 'STEP1-1', 1, 'ö', 'O');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('PHONE', 'STEP1-1', 1, 'Ö', 'O');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('PHONE', 'STEP1-2', 1, '(', '-');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('PHONE', 'STEP1-2', 1, ')', '-');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('PHONE', 'STEP1-2', 1, '-', '-');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('PHONE', 'STEP1-2', 1, '/', '-');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('PHONE', 'STEP1-2', 1, '\', '-');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('PHONE', 'STEP1-2', 1, '+', '-');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('TEST', 'STEP1-2', 1, '+', '-');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 2, ',@', '@');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('PHONE', 'STEP4', 2, '0090', 'x');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 3, 'HOTMAIL', 'HOTMAIL.COM');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('PHONE', 'STEP4', 3, '009', 'x');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 4, 'HOTMAİL', 'HOTMAIL.COM');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('PHONE', 'STEP4', 4, '090', 'x');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 5, 'HOTMAİLCOM', 'HOTMAIL.COM');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('PHONE', 'STEP4', 5, '90', 'x');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 6, 'HOTMAILCOM', 'HOTMAIL.COM');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('PHONE', 'STEP4', 6, '000', 'x');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 7, 'GMAİL', 'GMAIL.COM');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('PHONE', 'STEP4', 7, '0', 'x');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 8, '.coom', '.com');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 9, 'superonline', 'superonline.com');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 10, 'yahoo', 'yahoo.com');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 11, 'mynet', 'mynet.com');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 12, 'gmail', 'gmail.com');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 13, 'hotmail', 'hotmail.com');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 14, 'gmail', 'gmail.com');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 15, 'hotmailcom', 'hotmail.com');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 16, 'ş', 's');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 17, 'Ş', 's');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 18, 'ü', 'u');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 19, 'Ü', 'u');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 20, 'ğ', 'g');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 21, 'Ğ', 'g');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 22, 'ö', 'o');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 23, 'Ö', 'o');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 24, 'ı', 'i');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 25, 'İ', 'i');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 26, 'ç', 'c');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 27, 'Ç', 'c');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 28, 'comtr', 'com.tr');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 29, 'com.com.com.com.com', 'com');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 30, 'com.com.com.com', 'com');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 31, 'com.com.com', 'com');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 32, 'com.com', 'com');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 33, 'COM.COM.COM.COM.COM', 'COM');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 34, 'COM.COM.COM.COM', 'COM');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 35, 'COM.COM.COM', 'COM');
INSERT INTO REPLACEMENT_TABLE
(SUBJECT, STEP_NAME, RUN_ORDER, SEARCH_STRING, REPLACE_STRING)
VALUES('MAIL', 'STEP1', 36, 'COM.COM', 'COM');


create table MDM_CRM_PHN_STACK
(
  phone   VARCHAR2(300),
  dahili VARCHAR2(50),
  telno1 varchar2(300),
  telno2 varchar2(300),
  telno3 varchar2(300),
   CONSTRAINT phone_pk PRIMARY KEY (phone)
)

create table MDM_CRM_EMAIL_STACK
(
  emailaddress VARCHAR2(300),
isvalid number(1),
  email_processed varchar2(300),
  email_quality_code varchar2(300),
  CONSTRAINT emailaddress PRIMARY KEY (emailaddress)
)


CREATE TABLE DIC_ALLIANZ_CEP_ALAN_KOD (
AREACODE1 VARCHAR2(100),
AREACODE2 VARCHAR2(100)
);

INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('501','501');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('502','502');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('503','503');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('504','504');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('505','505');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('506','506');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('507','507');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('508','508');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('509','509');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('530','530');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('531','531');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('532','532');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('533','533');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('534','534');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('535','535');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('536','536');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('537','537');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('538','538');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('539','539');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('541','541');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('542','542');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('543','543');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('544','544');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('545','545');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('546','546');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('547','547');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('548','548');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('549','549');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('551','551');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('552','552');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('553','553');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('554','554');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('555','555');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('556','556');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('557','557');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('558','558');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('559','559');

COMMIT;

CREATE TABLE DIC_ALLIANZ_DAHILI_HAT (
INTVALUE VARCHAR(100),
STRINGVALUE VARCHAR2(100)
);


INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','DHLI');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','DAHILLI');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','D');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','DA');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','DH');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','DAH');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','DAHI');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','DAHIL');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','DAHLI');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','DAHILI');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('1','HAT');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','DHL');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('1','HA');


CREATE TABLE DIC_ALLIANZ_NOISE_TEL (
VALUE1 VARCHAR(100),
VALUE2 VARCHAR2(100)
);


INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','2121212');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','1000000');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','3232323');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','1111112');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','5000000');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','2000000');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','1212121');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','3000000');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','0000001');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','0000000');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','1111111');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','2222222');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','3333333');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','4444444');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','5555555');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','6666666');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','7777777');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','8888888');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','9999999');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','1231231');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','1234567');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','4564564');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','2111111');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','1112222');

commit;

CREATE TABLE DIC_ALLIANZ_SABIT_ALAN_KOD (
AREACODE1 VARCHAR2(100),
AREACODE2 VARCHAR2(100)
);

INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('212','212');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('216','216');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('222','222');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('224','224');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('226','226');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('228','228');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('232','232');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('236','236');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('242','242');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('246','246');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('248','248');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('252','252');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('256','256');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('258','258');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('262','262');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('264','264');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('266','266');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('272','272');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('274','274');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('276','276');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('282','282');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('284','284');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('286','286');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('288','288');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('312','312');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('318','318');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('322','322');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('324','324');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('326','326');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('328','328');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('332','332');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('338','338');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('342','342');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('344','344');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('346','346');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('348','348');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('352','352');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('354','354');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('356','356');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('358','358');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('362','362');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('364','364');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('366','366');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('368','368');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('370','370');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('372','372');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('374','374');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('376','376');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('378','378');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('380','380');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('382','382');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('384','384');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('386','386');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('388','388');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('392','392');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('412','412');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('414','414');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('416','416');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('422','422');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('424','424');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('426','426');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('428','428');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('432','432');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('434','434');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('436','436');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('438','438');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('442','442');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('446','446');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('452','452');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('454','454');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('456','456');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('458','458');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('462','462');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('464','464');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('466','466');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('472','472');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('474','474');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('476','476');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('478','478');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('482','482');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('484','484');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('486','486');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('488','488');

commit;