CREATE TABLE "QLICK"."DQ_SP_RUN_ORDER" 
   (	"SUBJECT_NAME" VARCHAR2(100), 
	"SP_NAME" VARCHAR2(100), 
	"RUN_ORDER" NUMBER(3,0), 
	"PARAMETER_NAME" VARCHAR2(250), 
	"PARAMETER_TYPE1" VARCHAR2(50), 
	"PARAMETER_TYPE2" VARCHAR2(50), 
	"PARAMETER_VALUE" VARCHAR2(300)
   )

INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('MAIL', 'PRC_EMAIL2_DECOMPOSITION', 2, 'var_domain_lower', 'OUT', 'varchar2', 'qgg');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('MAIL', 'PRC_EMAIL2_DECOMPOSITION', 2, 'var_email_reverse', 'OUT', 'varchar2', 'ii.ggq@1cejgf8');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('MAIL', 'PRC_EMAIL2_DECOMPOSITION', 2, 'exp_undefined_character', 'OUT', 'varchar2', NULL);
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('MAIL', 'PRC_EMAIL2_DECOMPOSITION', 2, 'exp_undefined_character_length', 'OUT', 'NUMBER', NULL);
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('MAIL', 'PRC_EMAIL2_DECOMPOSITION', 2, 'exp_email_subdomain', 'OUT', 'VARCHAR2', 'ii');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('MAIL', 'PRC_EMAIL2_DECOMPOSITION', 2, 'exp_email_user_name', 'OUT', 'VARCHAR2', '8fgjec1');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('MAIL', 'PRC_EMAIL2_DECOMPOSITION', 2, 'exp_email_user_name_length', 'OUT', 'NUMBER', '7');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('MAIL', 'PRC_EMAIL2_DECOMPOSITION', 2, 'std_email_without_symbol', 'OUT', 'VARCHAR2', '8fgjec1qggii');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('MAIL', 'PRC_EMAIL2_DECOMPOSITION', 2, 'exp_email_without_symbol_length', 'OUT', 'NUMBER', '12');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('MAIL', 'PRC_EMAIL2_DECOMPOSITION', 2, 'exp_email_character_first_order', 'OUT', 'NUMBER', '8');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('PHONE', 'PRC_PHN2_PROCESS_NUMBER', 1, 'in_telefon_numarasi', 'IN', 'VARCHAR2', '+9005311016093');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('MAIL', 'PRC_EMAIL2_DECOMPOSITION', 2, 'in_email', 'IN', 'varchar2', '8fgjec1@qgg.ii');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('MAIL', 'PRC_EMAIL2_DECOMPOSITION', 2, 'var_email_lower', 'OUT', 'varchar2', '8fgjec1@qgg.ii');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('PHONE', 'PRC_PHN2_PROCESS_NUMBER', 1, 'std_tel_no', 'OUT', 'VARCHAR2', '5311016093');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('PHONE', 'PRC_PHN2_PROCESS_NUMBER', 1, 'std_tel_no_for_decision', 'OUT', 'VARCHAR2', 'x5311016093');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('PHONE', 'PRC_PHN2_PROCESS_NUMBER', 1, 'lbl_tel_no', 'OUT', 'VARCHAR2', 'xddddddddddd');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('PHONE', 'PRC_PHN2_MOBILEHOME_CHCK', 2, 'p_std_tel_no', 'IN', 'VARCHAR2', '5311016093');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('PHONE', 'PRC_PHN2_MOBILEHOME_CHCK', 2, 'lbl_alan_kodu1', 'OUT', 'VARCHAR2', 'cep');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('PHONE', 'PRC_PHN2_MOBILEHOME_CHCK', 2, 'lbl_alan_kodu2', 'OUT', 'VARCHAR2', NULL);
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('PHONE', 'PRC_PHN2_EXTENSION_CHCK', 3, 'in_telefon_numarasi', 'IN', 'VARCHAR2', '+9005311016093');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('PHONE', 'PRC_PHN2_EXTENSION_CHCK', 3, 'hat_flag', 'OUT', 'NUMBER', '1');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('PHONE', 'PRC_PHN2_EXTENSION_CHCK', 3, 'dahili_flag', 'OUT', 'NUMBER', '0');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('PHONE', 'PRC_PHN2_DECISION', 4, 'lbl_tel_no', 'IN', 'VARCHAR2', 'xddddddddddd');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('PHONE', 'PRC_PHN2_DECISION', 4, 'std_tel_no_for_decision', 'IN', 'VARCHAR2', 'x5311016093');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('PHONE', 'PRC_PHN2_DECISION', 4, 'lbl_alan_kodu1', 'IN', 'VARCHAR2', 'cep');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('PHONE', 'PRC_PHN2_DECISION', 4, 'lbl_alan_kodu2', 'IN', 'VARCHAR2', NULL);
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('PHONE', 'PRC_PHN2_DECISION', 4, 'dahili_flag', 'IN', 'NUMBER', '0');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('PHONE', 'PRC_PHN2_DECISION', 4, 'hat_flag', 'IN', 'NUMBER', '1');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('PHONE', 'PRC_PHN2_DECISION', 4, 'dec_telefon_no1', 'OUT', 'VARCHAR2', '5311016093');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('PHONE', 'PRC_PHN2_DECISION', 4, 'dec_telefon_no2', 'OUT', 'VARCHAR2', NULL);
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('PHONE', 'PRC_PHN2_DECISION', 4, 'dec_telefon_no3', 'OUT', 'VARCHAR2', NULL);
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('PHONE', 'PRC_PHN2_DECISION', 4, 'dec_dahili_no', 'OUT', 'VARCHAR2', NULL);
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('PHONE', 'PRC_PHN2_VALIDATION', 5, 'dec_dahili_no_in', 'IN', 'VARCHAR2', NULL);
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('PHONE', 'PRC_PHN2_VALIDATION', 5, 'dec_telefon_no1', 'IN', 'VARCHAR2', '5311016093');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('PHONE', 'PRC_PHN2_VALIDATION', 5, 'dec_telefon_no2', 'IN', 'VARCHAR2', NULL);
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('PHONE', 'PRC_PHN2_VALIDATION', 5, 'dec_telefon_no3', 'IN', 'VARCHAR2', NULL);
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('PHONE', 'PRC_PHN2_VALIDATION', 5, 'dec_dahili_no_out', 'OUT', 'VARCHAR2', NULL);
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('PHONE', 'PRC_PHN2_VALIDATION', 5, 'telno1', 'OUT', 'VARCHAR2', '5311016093');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('PHONE', 'PRC_PHN2_VALIDATION', 5, 'telno2', 'OUT', 'VARCHAR2', NULL);
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('PHONE', 'PRC_PHN2_VALIDATION', 5, 'telno3', 'OUT', 'VARCHAR2', NULL);
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('MAIL', 'PRC_EMAIL2_PRE_PROCESS', 1, 'vEmail', 'IN', 'Varchar2', '8fGjEC1@qgg.ii');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('MAIL', 'PRC_EMAIL2_PRE_PROCESS', 1, 'in_email', 'OUT', 'Varchar2', '8fgjec1@qgg.ii');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('MAIL', 'PRC_EMAIL2_VALIDATION', 3, 'exp_email_subdomain', 'IN', 'varchar2', 'ii');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('MAIL', 'PRC_EMAIL2_VALIDATION', 3, 'exp_email_user_name', 'IN', 'varchar2', '8fgjec1');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('MAIL', 'PRC_EMAIL2_VALIDATION', 3, 'Tkn_subdomain_pattern', 'OUT', 'varchar2', 'invalid');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('MAIL', 'PRC_EMAIL2_VALIDATION', 3, 'TokenizedData2', 'OUT', 'varchar2', 'invalid');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('MAIL', 'PRC_EMAIL2_VALIDATION', 3, 'Tkn_username_noise', 'OUT', 'varchar2', 'invalid');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('MAIL', 'PRC_EMAIL2_VALIDATION', 3, 'tokenizedData5', 'OUT', 'varchar2', 'invalid');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('MAIL', 'PRC_EMAIL2_CHECK_QUALITY', 4, 'in_email', 'IN', 'VARCHAR2', '8fgjec1@qgg.ii');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('MAIL', 'PRC_EMAIL2_CHECK_QUALITY', 4, 'exp_undefined_character_length', 'IN', 'NUMBER', NULL);
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('MAIL', 'PRC_EMAIL2_CHECK_QUALITY', 4, 'exp_email_without_symbol_length', 'IN', 'NUMBER', '12');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('MAIL', 'PRC_EMAIL2_CHECK_QUALITY', 4, 'exp_email_user_name_length', 'IN', 'number', '7');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('MAIL', 'PRC_EMAIL2_CHECK_QUALITY', 4, 'exp_email_character_first_order', 'IN', 'NUMBER', '8');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('MAIL', 'PRC_EMAIL2_CHECK_QUALITY', 4, 'tkn_username_noise', 'IN', 'VARCHAR2', 'invalid');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('MAIL', 'PRC_EMAIL2_CHECK_QUALITY', 4, 'tkn_subdomain_pattern', 'IN', 'VARCHAR2', 'invalid');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('MAIL', 'PRC_EMAIL2_CHECK_QUALITY', 4, 'dec_email_quality_detail_code', 'OUT', 'VARCHAR2', 'emlprb09');
INSERT INTO DQ_SP_RUN_ORDER (SUBJECT_NAME, SP_NAME, RUN_ORDER, PARAMETER_NAME, PARAMETER_TYPE1, PARAMETER_TYPE2, PARAMETER_VALUE) VALUES('MAIL', 'PRC_EMAIL2_CHECK_QUALITY', 4, 'dec_cl_email', 'OUT', 'VARCHAR2', NULL);