'0','DHLI'
'0','DAHILLI'
'0','D'
'0','DA'
'0','DH'
'0','DAH'
'0','DAHI'
'0','DAHIL'
'0','DAHLI'
'0','DAHILI'
'1','HAT'
'0','DHL'
'1','HA'


CREATE TABLE DIC_ALLIANZ_DAHILI_HAT (
INTVALUE VARCHAR(100),
STRINGVALUE VARCHAR2(100)
)


INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES(


INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','DHLI');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','DAHILLI');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','D');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','DA');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','DH');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','DAH');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','DAHI');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','DAHIL');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','DAHLI');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','DAHILI');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('1','HAT');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','DHL');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('1','HA');

SELECT * FROM DIC_ALLIANZ_DAHILI_HAT 