-------------------------necessary tables---------------------------------------


CREATE TABLE DIC_ALLIANZ_CEP_ALAN_KOD (
AREACODE1 VARCHAR2(100),
AREACODE2 VARCHAR2(100)
)


INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES(

INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('501','501');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('502','502');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('503','503');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('504','504');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('505','505');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('506','506');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('507','507');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('508','508');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('509','509');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('530','530');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('531','531');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('532','532');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('533','533');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('534','534');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('535','535');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('536','536');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('537','537');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('538','538');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('539','539');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('541','541');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('542','542');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('543','543');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('544','544');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('545','545');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('546','546');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('547','547');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('548','548');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('549','549');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('551','551');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('552','552');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('553','553');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('554','554');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('555','555');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('556','556');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('557','557');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('558','558');
INSERT INTO DIC_ALLIANZ_CEP_ALAN_KOD VALUES('559','559');

COMMIT

SELECT * FROM DIC_ALLIANZ_CEP_ALAN_KOD 

CREATE TABLE DIC_ALLIANZ_DAHILI_HAT (
INTVALUE VARCHAR(100),
STRINGVALUE VARCHAR2(100)
)

INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','DHLI');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','DAHILLI');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','D');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','DA');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','DH');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','DAH');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','DAHI');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','DAHIL');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','DAHLI');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','DAHILI');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('1','HAT');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('0','DHL');
INSERT INTO DIC_ALLIANZ_DAHILI_HAT VALUES('1','HA');

SELECT * FROM DIC_ALLIANZ_DAHILI_HAT 


CREATE TABLE DIC_ALLIANZ_NOISE_TEL (
VALUE1 VARCHAR(100),
VALUE2 VARCHAR2(100)
)


INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','2121212');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','1000000');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','3232323');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','1111112');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','5000000');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','2000000');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','1212121');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','3000000');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','0000001');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','0000000');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','1111111');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','2222222');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','3333333');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','4444444');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','5555555');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','6666666');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','7777777');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','8888888');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','9999999');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','1231231');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','1234567');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','4564564');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','2111111');
INSERT INTO DIC_ALLIANZ_NOISE_TEL VALUES('noise','1112222');

SELECT * FROM DIC_ALLIANZ_NOISE_TEL

COMMIT



CREATE TABLE DIC_ALLIANZ_SABIT_ALAN_KOD (
AREACODE1 VARCHAR2(100),
AREACODE2 VARCHAR2(100)
)

INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('212','212');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('216','216');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('222','222');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('224','224');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('226','226');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('228','228');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('232','232');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('236','236');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('242','242');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('246','246');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('248','248');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('252','252');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('256','256');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('258','258');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('262','262');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('264','264');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('266','266');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('272','272');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('274','274');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('276','276');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('282','282');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('284','284');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('286','286');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('288','288');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('312','312');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('318','318');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('322','322');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('324','324');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('326','326');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('328','328');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('332','332');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('338','338');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('342','342');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('344','344');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('346','346');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('348','348');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('352','352');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('354','354');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('356','356');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('358','358');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('362','362');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('364','364');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('366','366');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('368','368');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('370','370');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('372','372');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('374','374');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('376','376');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('378','378');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('380','380');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('382','382');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('384','384');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('386','386');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('388','388');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('392','392');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('412','412');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('414','414');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('416','416');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('422','422');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('424','424');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('426','426');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('428','428');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('432','432');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('434','434');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('436','436');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('438','438');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('442','442');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('446','446');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('452','452');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('454','454');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('456','456');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('458','458');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('462','462');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('464','464');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('466','466');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('472','472');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('474','474');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('476','476');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('478','478');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('482','482');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('484','484');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('486','486');
INSERT INTO DIC_ALLIANZ_SABIT_ALAN_KOD VALUES('488','488');

commit

SELECT * FROM DIC_ALLIANZ_SABIT_ALAN_KOD

-----------------------------PRC_PHN_PROCESS_NUMBER-----------------------------

DECLARE
    in_telefon_numarasi VARCHAR2(100) := '+9005311016093'; -- Provide the actual phone number
    std_tel_no VARCHAR2(100);
    std_tel_no_for_decision VARCHAR2(100);
    lbl_tel_no VARCHAR2(100);

BEGIN
    -- Call the stored procedure
    QLICK.PRC_PHN_PROCESS_NUMBER(in_telefon_numarasi, std_tel_no,std_tel_no_for_decision,lbl_tel_no);

    -- Display the processed phone number
    DBMS_OUTPUT.PUT_LINE('Original Phone Number: ' || in_telefon_numarasi);
    DBMS_OUTPUT.PUT_LINE('Processed Phone Number: ' || std_tel_no);
    DBMS_OUTPUT.PUT_LINE('std_tel_no_for_decision: ' || std_tel_no_for_decision);
    DBMS_OUTPUT.PUT_LINE('Labelled Phone Number: ' || lbl_tel_no);

END;
-----------------------------PRC_PHN_MOBILEHOME_CHCK-----------------------------
DECLARE
    p_std_tel_no VARCHAR2(100) := '5311016093'; -- Provide the actual phone number
    lbl_alan_kodu1 VARCHAR2(10);
    lbl_alan_kodu2 VARCHAR2(10);
BEGIN
    -- Call the procedure
    QLICK.PRC_PHN_MOBILEHOME_CHCK(p_std_tel_no, lbl_alan_kodu1, lbl_alan_kodu2);

    -- Display the results
    DBMS_OUTPUT.PUT_LINE('Phone Number: ' || p_std_tel_no);
    DBMS_OUTPUT.PUT_LINE('Label for Area Code 1: ' || lbl_alan_kodu1);
    DBMS_OUTPUT.PUT_LINE('Label for Area Code 2: ' || lbl_alan_kodu2);

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END;

-----------------------------PRC_PHN_EXTENSION_CHCK-----------------------------
DECLARE
    p_std_tel_no VARCHAR2(100) := '5311016093DAH'; -- Provide the actual phone number
    hat_flag NUMBER(1);
    dahili_flag NUMBER(1);
BEGIN
    -- Call the procedure
    QLICK.PRC_PHN_EXTENSION_CHCK(p_std_tel_no, hat_flag, dahili_flag);

    -- Display the results
    DBMS_OUTPUT.PUT_LINE('Phone Number: ' || p_std_tel_no);
    DBMS_OUTPUT.PUT_LINE('hat_flag: ' || hat_flag);
    DBMS_OUTPUT.PUT_LINE('dahili_flag: ' || dahili_flag);

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END;

-----------------------PRC_PHONE_DECISION-------------------------------------------

DECLARE
    -- Declare variables to hold input parameters
    lbl_tel_no_param   VARCHAR2(20) := 'xdddddddddd';
    std_tel_no_param   VARCHAR2(20) := 'x5311016093';
    lbl_alan_kodu1_param VARCHAR2(20) := 'cep';
    lbl_alan_kodu2_param VARCHAR2(20) := '';
    dahili_flag_param   NUMBER := 1;
    hat_flag_param      NUMBER := 0;

    -- Declare variables to hold output parameters
    dec_telefon_no1    VARCHAR2(20);
    dec_telefon_no2    VARCHAR2(20);
    dec_telefon_no3    VARCHAR2(20);
    dec_dahili_no      VARCHAR2(20);

BEGIN
    -- Call the procedure
    QLICK.PRC_PHN_DECISION(
        lbl_tel_no_param,
        std_tel_no_param,
        lbl_alan_kodu1_param,
        lbl_alan_kodu2_param,
        dahili_flag_param,
        hat_flag_param,
        dec_telefon_no1,
        dec_telefon_no2,
        dec_telefon_no3,
        dec_dahili_no
    );

    -- Print the output values
    dbms_output.put_line('dec_telefon_no1: ' || dec_telefon_no1);
    dbms_output.put_line('dec_telefon_no2: ' || dec_telefon_no2);
    dbms_output.put_line('dec_telefon_no3: ' || dec_telefon_no3);
    dbms_output.put_line('dec_dahili_no: ' || dec_dahili_no);
END;

-----------------------PRC_PHN_VALIDATION-------------------------------------------

DECLARE
    v_dec_dahili_no_in   VARCHAR2(50) := '';
    v_dec_telefon_no1    VARCHAR2(50) := '2564567890';
    v_dec_telefon_no2    VARCHAR2(50) := '9876543210';
    v_dec_telefon_no3    VARCHAR2(50) := '5555555555';
    v_dec_dahili_no_out  VARCHAR2(50);
    v_telno1             VARCHAR2(50);
    v_telno2             VARCHAR2(50);
    v_telno3             VARCHAR2(50);
BEGIN
    PRC_PHN_VALIDATION(
        v_dec_dahili_no_in,
        v_dec_telefon_no1,
        v_dec_telefon_no2,
        v_dec_telefon_no3,
        v_dec_dahili_no_out,
        v_telno1,
        v_telno2,
        v_telno3
    );

    -- Display the output using DBMS_OUTPUT
    DBMS_OUTPUT.PUT_LINE('dec_dahili_no_out: ' || v_dec_dahili_no_out);
    DBMS_OUTPUT.PUT_LINE('telno1: ' || v_telno1);
    DBMS_OUTPUT.PUT_LINE('telno2: ' || v_telno2);
    DBMS_OUTPUT.PUT_LINE('telno3: ' || v_telno3);
END;

-----------------------------PRC_PHN_MAIN_PROCESS------------------------------------------------
DECLARE
    in_telefon_numarasi VARCHAR2(50) := '+9005311016093';  -- Replace with an actual phone number
    dec_dahili_no_out VARCHAR2(50);
    telno1 VARCHAR2(300);
    telno2 VARCHAR2(300);
    telno3 VARCHAR2(300);
BEGIN
    -- Call the procedure with the provided input
    QLICK.PRC_PHN_MAIN_PROCESS(in_telefon_numarasi, dec_dahili_no_out, telno1, telno2, telno3);

    -- Display the output using DBMS_OUTPUT
    DBMS_OUTPUT.PUT_LINE('Input Phone Number: ' || in_telefon_numarasi);
    DBMS_OUTPUT.PUT_LINE('Dec Dahili No: ' || dec_dahili_no_out);
    DBMS_OUTPUT.PUT_LINE('Tel No 1: ' || telno1);
    DBMS_OUTPUT.PUT_LINE('Tel No 2: ' || telno2);
    DBMS_OUTPUT.PUT_LINE('Tel No 3: ' || telno3);
END;



DECLARE
    in_telefon_numarasi VARCHAR2(50) := '+9005311016093';  -- Replace with an actual phone number
    dec_dahili_no_out VARCHAR2(50);
    telno1 VARCHAR2(300);
    telno2 VARCHAR2(300);
    telno3 VARCHAR2(300);
BEGIN
    -- Call the procedure with the provided input
    QLICK.PRC_PHN2_MAIN_PROCESS(in_telefon_numarasi, dec_dahili_no_out, telno1, telno2, telno3);

    -- Display the output using DBMS_OUTPUT
    DBMS_OUTPUT.PUT_LINE('Input Phone Number: ' || in_telefon_numarasi);
    DBMS_OUTPUT.PUT_LINE('Dec Dahili No: ' || dec_dahili_no_out);
    DBMS_OUTPUT.PUT_LINE('Tel No 1: ' || telno1);
    DBMS_OUTPUT.PUT_LINE('Tel No 2: ' || telno2);
    DBMS_OUTPUT.PUT_LINE('Tel No 3: ' || telno3);
END;
------------------------------------------END--------------------------------------------------------

