SELECT /*+PARALLEL(CONTACT 16) PARALLEL(COMM 16) PARALLEL(ADDR 16) PARALLEL(ACC 16)*/
COALESCE(CONTACT.DELTA_VALUE_KEY,ACC.DELTA_VALUE_KEY,COMM.DELTA_VALUE_KEY,ADDR.DELTA_VALUE_KEY) AS DELTA_VALUE_KEY,  ----!!!
COALESCE(CONTACT.HISTORYNO,ACC.HISTORYNO,COMM.HISTORYNO,ADDR.HISTORYNO)  AS HISTORYNO,        ----!!!
CONTACT.IDENTITYNUMBER AS IDENTITYNUMBER,
CONTACT.FOREIGNIDENTITYNUMBER AS FOREIGNIDENTITYNUMBER,
COALESCE(CONTACT.TAXNO,ACC.TAX_NUMBER,COMM.IDENTITY_TAX_NUMBER,ADDR.IDENTITY_TAX_NUMBER) AS TAXNO,
CONTACT.FIRSTNAME AS FIRSTNAME,
CONTACT.LASTNAME AS LASTNAME,
CONTACT.BIRTHDATE AS BIRTHDATE,
CONTACT.BIRTHPLACEID AS BIRTHPLACEID,
CONTACT.MOTHERNAME AS MOTHERNAME,
CONTACT.FATHERNAME AS FATHERNAME,
CONTACT.NATIONALITY AS NATIONALITY,
CONTACT.GENDERCODE AS GENDERCODE,
CONTACT.FAMILYSTATUSCODE AS FAMILYSTATUSCODE,
CONTACT.PASSPORTNO AS PASSPORTNO,
CONTACT.DATEOFDEATH AS DATEOFDEATH,
CONTACT.CODEOFDEATH AS CODEOFDEATH,
NULL AS ANNIVERSARY,
CONTACT.NUMBEROFCHILDREN AS NUMBEROFCHILDREN,
CONTACT.IDENTITYCARDTYPE AS IDENTITYCARDTYPE,
CONTACT.EDUCATIONSTATUS AS EDUCATIONSTATUS,
CONTACT.PROFESSIONID AS PROFESSIONID,
NULL AS COMPANYNAME,
NULL AS SECTORID,
NULL AS RETIREMENTDATE,
NULL AS EFFECTIVEDATE,
COMM.MOBILEPHONE AS MOBILEPHONE,
COMM.TELEPHONE3 AS TELEPHONE3,
COMM.EMAILADDRESS1 AS EMAILADDRESS1,
NULL AS COUNTRYID,
NULL AS CITYID,
NULL AS COUNTYID,
ADDR.POSTAL_CD AS POSTALCODE,
ADDR.ADDRESSDETAIL AS ADDRESSDETAIL,
CONTACT.KPSQUERYDATE AS KPSQUERYDATE,
COMM.CDVGSMINFO AS CDVGSMINFO,
COMM.CDVEMAILINFO AS CDVEMAILINFO,
NULL AS BLACKLISTFLAG,
NULL AS MOBILAPPUSAGE,
NULL AS HAVETAXADVANTAGE,
NULL AS SEGMENTCODE,
NULL AS MEMBEROF365,
NULL AS OWNEROFCUSTOMER,
NULL AS LASTINTERVIEWER,
NULL AS LASTINTERVIEWDATE,
NULL AS FUNDCHANGEDATE,
NULL AS ISKOCMEMBER,
null as IDENTITYNUMBER_DT,          --------EK ALANLAR START-------
NULL FOREIGNIDENTITYNUMBER_DT,
NULL AS TAXNO_DT,
CONTACT.FIRSTNAME_DT,
CONTACT.LASTNAME_DT,
CONTACT.BIRTHDATE_DT,
CONTACT.BIRTHPLACEID_DT,
CONTACT.MOTHERNAME_DT,
CONTACT.FATHERNAME_DT,
CONTACT.NATIONALITY_DT,
CONTACT.GENDERCODE_DT,
CONTACT.FAMILYSTATUSCODE_DT,
CONTACT.PASSORTNO_DT AS PASSPORTNO_DT,
CONTACT.DATEOFDEATH_DT,
CONTACT.CODEOFDEATH_DT,
NULL AS ANNIVERSARY_DT,
CONTACT.NUMBEROFCHILDREN_DT,
NULL AS IDENTITYCARDTYPE_DT,
CONTACT.EDUCATIONSTATUS_DT,
CONTACT.PROFESSIONID_DT,
NULL AS COMPANYNAME_DT,
NULL AS SECTORID_DT,
NULL AS RETIREMENTDATE_DT,
NULL AS EFFECTIVEDATE_DT,
COMM.MOBILEPHONE_DT,
COMM.TELEPHONE3_DT,
COMM.EMAILADDRESS1_DT,
NULL AS COUNTRYID_DT,
NULL AS CITYID_DT,
NULL AS COUNTYID_DT,
ADDR.POSTAL_CD_DT AS  POSTALCODE_DT,
ADDR.ADDRESSDETAIL_DT,
CONTACT.KPSQUERYDATE_DT,
COMM.CDVGSMINFO_DT,
COMM.CDVEMAILINFO_DT,
NULL AS BLACKLISTFLAG_DT,
NULL AS MOBILAPPUSAGE_DT,
NULL AS HAVETAXADVANTAGE_DT,
NULL AS SEGMENTCODE_DT,
NULL AS MEMBEROF365_DT,
NULL AS OWNEROFCUSTOMER_DT,
NULL AS LASTINTERVIEWER_DT,
NULL AS LASTINTERVIEWDATE_DT,
NULL AS FUNDCHANGEDATE_DT,
NULL AS ISKOCMEMBER_DT
FROM
COMPOSECRML2.TDWH_CRM_ABS_MAIN_CONTACT_HUB CONTACT
  FULL OUTER JOIN 
    COMPOSECRML2.TDWH_CRM_ABS_COMM_HUB COMM 
  ON CONTACT.DELTA_VALUE_KEY=COMM.DELTA_VALUE_KEY
     AND  CONTACT.HISTORYNO=COMM.HISTORYNO    
    FULL OUTER JOIN
     COMPOSECRML2.TDWH_CRM_ABS_ADDR_HUB ADDR
  ON COMM.DELTA_VALUE_KEY=ADDR.DELTA_VALUE_KEY
     AND  COMM.HISTORYNO=ADDR.HISTORYNO
    FULL OUTER JOIN
     COMPOSECRML2.TDWH_CRM_ABS_MAIN_ACCOUNT_HUB ACC
  ON ADDR.DELTA_VALUE_KEY=ACC.DELTA_VALUE_KEY
     AND  ADDR.HISTORYNO=ACC.HISTORYNO
	 
------------------------------------------------------------------------------------------------------------------------

SELECT /*+PARALLEL(CONTACT 16) PARALLEL(COMM 16) PARALLEL(ADDR 16) PARALLEL(ACC 16)*/
CONTACT.DELTA_VALUE_KEY,  ----!!!
NULL AS HISTORYNO,        ----!!!
CONTACT.IDENTITYNUMBER AS IDENTITYNUMBER,
CONTACT.FOREIGNIDENTITYNUMBER AS FOREIGNIDENTITYNUMBER,
COALESCE(CONTACT.TAXNO,ACC.TAX_NUMBER,COMM.IDENTITY_TAX_NUMBER,ADDR.IDENTITY_TAX_NUMBER) AS TAXNO,
CONTACT.FIRSTNAME AS FIRSTNAME,
CONTACT.LASTNAME AS LASTNAME,
CONTACT.BIRTHDATE AS BIRTHDATE,
CONTACT.BIRTHPLACEID AS BIRTHPLACEID,
CONTACT.MOTHERNAME AS MOTHERNAME,
CONTACT.FATHERNAME AS FATHERNAME,
CONTACT.NATIONALITY AS NATIONALITY,
CONTACT.GENDERCODE AS GENDERCODE,
CONTACT.FAMILYSTATUSCODE AS FAMILYSTATUSCODE,
CONTACT.PASSPORTNO AS PASSPORTNO,
CONTACT.DATEOFDEATH AS DATEOFDEATH,
CONTACT.CODEOFDEATH AS CODEOFDEATH,
NULL AS ANNIVERSARY,
CONTACT.NUMBEROFCHILDREN AS NUMBEROFCHILDREN,
CONTACT.IDENTITYCARDTYPE AS IDENTITYCARDTYPE,
CONTACT.EDUCATIONSTATUS AS EDUCATIONSTATUS,
CONTACT.PROFESSIONID AS PROFESSIONID,
NULL AS COMPANYNAME,
NULL AS SECTORID,
NULL AS RETIREMENTDATE,
CONTACT.EFFECTIVEDATE AS EFFECTIVEDATE,
COMM.MOBILEPHONE AS MOBILEPHONE,
COMM.TELEPHONE3 AS TELEPHONE3,
COMM.EMAILADDRESS1 AS EMAILADDRESS1,
ADDR.COUNTRY_CODE AS COUNTRYID,
ADDR.CITY_CODE AS CITYID,
NULL AS COUNTYID,
ADDR.POSTCODE AS POSTALCODE,
ADDR.ADDRESSDETAIL AS ADDRESSDETAIL,
CONTACT.KPSQUERYDT AS KPSQUERYDATE,
COMM.CDVGSMINFO AS CDVGSMINFO,
COMM.CDVEMAILINFO AS CDVEMAILINFO,
CONTACT.BLACKLISTFLAG AS BLACKLISTFLAG,
NULL AS MOBILAPPUSAGE,
NULL AS HAVETAXADVANTAGE,
NULL AS SEGMENTCODE,
NULL AS MEMBEROF365,
NULL AS OWNEROFCUSTOMER,
NULL AS LASTINTERVIEWER,
NULL AS LASTINTERVIEWDATE,
NULL AS FUNDCHANGEDATE,
NULL AS ISKOCMEMBER,
CONTACT.IDENTITYNUMBER_DT,      --------EK ALANLAR START-------
CONTACT.FOREIGNIDENTITYNUMBER_DT,
CONTACT.TAXNO_DT,
CONTACT.FIRSTNAME_DT,
CONTACT.LASTNAME_DT,
CONTACT.BIRTHDATE_DT,
CONTACT.BIRTHPLACEID_DT,
CONTACT.MOTHERNAME_DT,
CONTACT.FATHERNAME_DT,
CONTACT.NATIONALITY_DT,
CONTACT.GENDERCODE_DT,
CONTACT.FAMILYSTATUSCODE_DT,
CONTACT.PASSPORTNO_DT,
CONTACT.DATEOFDEATH_DT,
CONTACT.CODEOFDEATH_DT,
NULL AS ANNIVERSARY_DT,
CONTACT.NUMBEROFCHILDREN_DT,
NULL AS IDENTITYCARDTYPE_DT,
CONTACT.EDUCATIONSTATUS_DT,
CONTACT.PROFESSIONID_DT,
NULL AS COMPANYNAME_DT,
NULL AS SECTORID_DT,
NULL AS RETIREMENTDATE_DT,
CONTACT.EFFECTIVEDATE_DT,
COMM.MOBILEPHONE_DT,
COMM.TELEPHONE3_DT,
COMM.EMAILADDRESS1_DT,
ADDR.COUNTRY_CODE_DT AS COUNTRYID_DT,
ADDR.CITY_CODE_DT AS CITYID_DT,
NULL AS COUNTYID_DT,
ADDR.POSTCODE_DT AS  POSTALCODE_DT,
ADDR.ADDRESSDETAIL_DT,
CONTACT.KPSQUERYDATE_DT,
COMM.CDVGSMINFO_DT,
COMM.CDVEMAILINFO_DT,
NULL AS BLACKLISTFLAG_DT,
NULL AS MOBILAPPUSAGE_DT,
NULL AS HAVETAXADVANTAGE_DT,
NULL AS SEGMENTCODE_DT,
NULL AS MEMBEROF365_DT,
NULL AS OWNEROFCUSTOMER_DT,
NULL AS LASTINTERVIEWER_DT,
NULL AS LASTINTERVIEWDATE_DT,
NULL AS FUNDCHANGEDATE_DT,
NULL AS ISKOCMEMBER_DT
FROM
COMPOSECRML2.TDWH_CRM_AZS_MAIN_CONTACT_HUB CONTACT
	FULL OUTER JOIN 
		COMPOSECRML2.TDWH_CRM_AZS_COMM_HUB COMM 
	ON CONTACT.DELTA_VALUE_KEY=COMM.DELTA_VALUE_KEY
	   AND  CONTACT.HISTORYNO=COMM.HISTORYNO		
    FULL OUTER JOIN
	   COMPOSECRML2.TDWH_CRM_AZS_ADDR_HUB ADDR
	ON COMM.DELTA_VALUE_KEY=ADDR.DELTA_VALUE_KEY
	   AND  COMM.HISTORYNO=ADDR.HISTORYNO
    FULL OUTER JOIN
	   COMPOSECRML2.TDWH_CRM_AZS_MAIN_ACCOUNT_HUB ACC
	ON ADDR.DELTA_VALUE_KEY=ACC.DELTA_VALUE_KEY
	   AND  ADDR.HISTORYNO=ACC.HISTORYNO




  AND  sub.DELTA_VALUE_KEY=CONCAT.DELTA_VALUE_KEY(+)
  AND  sub.HISTORYNO=CONCAT.HISTORYNO(+)
  AND  sub.DELTA_VALUE_KEY=COMM.DELTA_VALUE_KEY(+)
  AND  sub.HISTORYNO=COMM.HISTORYNO(+)
  AND  sub.DELTA_VALUE_KEY=ADDR.DELTA_VALUE_KEY(+)
  AND  sub.HISTORYNO=ADDR.HISTORYNO(+)
  AND  sub.DELTA_VALUE_KEY=ACC.DELTA_VALUE_KEY(+)
  AND  sub.HISTORYNO=ACC.HISTORYNO(+)